var Archetypes = [
  "Ally of Justice",
  "Genex",
  "R-Genex",
  "Genex Ally",
  "Horus the Black Flame Dragon",
  "Amazoness",
  "Arcana Force",
  "Dark World",
  "Ancient Gear",
  "HERO",
  "Elemental HERO",
  "Vision HERO",
  "Evil HERO",
  "Masked HERO",
  "Destiny HERO",
  "Neos",
  "lswarm",
  "Steelswarm",
  "Infernity",
  "Alien",
  "Saber",
  "X-Saber",
  "XX-Saber",
  "Elementsaber",
  "Watt",
  "Ojama",
  "Gusto",
  "Karakuri",
  "Frog",
  "Meklord",
  "Meklord Emperor",
  "Meklord Army",
  "Allure Queen",
  "B.E.S.",
  "roid",
  "Vehicroid",
  "Speedroid",
  "Synchro",
  "Synchron",
  "Synchro Dragon",
  "Cloudian",
  "Gladiator Beast",
  "Dark Scorpion",
  "Phantom Beast",
  "Mecha Phantom Beast",
  "Spirit Message",
  "Koa'ki Meiru",
  "Chrysalis",
  "Neo-Spacian",
  "Shien",
  "Earthbound Immortal",
  "Jurrac",
  "Malefic",
  "Scrap",
  "Iron Chain",
  "Morphtronic",
  "T.G.",
  "Batteryman",
  "Dragunity",
  "Naturia",
  "Ninja",
  "Armor Ninja",
  "Flamvell",
  "Nitro",
  "Gravekeeper's",
  "Ice Barrier",
  "Vylon",
  "Fortune Lady",
  "Volcanic",
  "Blackwing",
  "Assault Blackwing",
  "Crystal",
  "Crystal Beast",
  "Ultimate Crystal",
  "Fabled",
  "Machina",
  "Mist Valley",
  "Lightsworn",
  "Laval",
  "Gishki",
  "Red-Eyes",
  "Reptilianne",
  "Six Samurai",
  "Secret Six Samurai",
  "Worm",
  "Majestic",
  "Forbidden One",
  "LV",
  "Nordic",
  "Nordic Ascendant",
  "Nordic Beast",
  "Nordic Alfar",
  "Nordic Relic",
  "Junk",
  "The Agent",
  "Archfiend",
  "Red Dragon Archfiend",
  "Polymerization/Fusion",
  "Fusion Dragon",
  "Gem-",
  "Gem-Knight",
  "Number",
  "Number C",
  "Number C39",
  "Skyblaster",
  "Timelord",
  "Aesir",
  "Trap Hole",
  "Beast's Battle",
  "Evol",
  "Evoltile",
  "Evolsaur",
  "Evolzar",
  "/Assault Mode",
  "Venom",
  "Starving Venom",
  "Gadget",
  "Guardian",
  "Constellar",
  "Gagaga",
  "Photon",
  "Inzektor",
  "Resonator",
  "Wind-Up",
  "Gogogo",
  "Penguin",
  "Inmato",
  "Sphinx",
  "Bamboo Sword",
  "Ninjitsu Art",
  "Toon",
  "Reactor",
  "Harpie",
  "Infestation",
  "Warrior",
  "Symphonic Warrior",
  "Magnet Warrior",
  "Iron",
  "Tin",
  "Hieratic",
  "Butterspy",
  "Bounzer",
  "Lightray",
  "Djinn",
  "Djinn of Rituals",
  "Prophecy",
  "Spellbook",
  "Heroic",
  "Heroic Challenger",
  "Heroic Champion",
  "Chronomaly",
  "Madolche",
  "Geargia",
  "Geargiano",
  "Xyz",
  "CXyz",
  "Xyz Dragon",
  "Mermail",
  "Abyss-",
  "Heraldic Beast",
  "Atlantean",
  "Nimble",
  "Fire Fist",
  "Noble",
  "Noble Knight",
  "Noble Arms",
  "Galaxy",
  "Galaxy-Eyes",
  "Galaxy-Eyes Tachyon Dragon",
  "Fire Formation",
  "Hazy",
  "Hazy Flame",
  "ZW",
  "Utopi/c",
  "Utopia",
  "Duston",
  "Fire King",
  "Fire King Avatar",
  "Dododo",
  "Gimmick Puppet",
  "Battlin' Boxer",
  "Super Defense Robot",
  "Star Seraph",
  "Umbral Horror",
  "Bujin",
  "Hole",
  "Envy",
  "Traptrix",
  "Malicevorous",
  "Druid",
  "Ghostrick",
  "Vampire",
  "Zubaba",
  "Sylvan",
  "Necrovalley",
  "Heraldry",
  "Cyber",
  "Cyber Dragon",
  "Cyber Angel",
  "Cyberdark",
  "Cybernetic",
  "Rank-Up-Magic",
  "Fishborg",
  "Artifact",
  "Magician",
  "Odd-Eyes",
  "Superheavy Samurai",
  "Superheavy Samurai Soul",
  "Melodious",
  "Melodious Maestra",
  "tellarknight",
  "Stellarknight",
  "Shaddoll",
  "Yang Zing",
  "Performapal",
  "Legendary Knight",
  "Legendary Dragon",
  "Magician",
  "Dark Magician",
  "Magician Girl",
  "Dark Magician Girl",
  "Stardust",
  "Kuriboh",
  "Winged Kuriboh",
  "Change",
  "sprout",
  "Artorigus",
  "Laundsallyn",
  "Fluffal",
  "Qli",
  "Apoqliphort",
  "Deskbot",
  "Goblin",
  "Frightfur",
  "Dark Contract",
  "D/D",
  "D/D/D",
  "Gottoms",
  "Burning Abyss",
  "U.A.",
  "Yosenju",
  "Nekroz",
  "Ritual Beast",
  "Ritual Beast Tamer",
  "Spiritual Beast",
  "Spiritual Beast Tamer",
  "Ritual Beast Ulti-",
  "Entity",
  "Outer Entity",
  "Elder Entity",
  "Old Entity",
  "Blaze Accelerator",
  "Raidraptor",
  "Infernoid",
  "Jinzo",
  "Gaia The Fierce Knight",
  "Monarch",
  "Charmer",
  "Familiar-Possessed",
  "PSY-Frame",
  "PSY-Framegear",
  "Power Tool",
  "Edge Imp",
  "Zefra",
  "Void",
  "Performage",
  "Dracoslayer",
  "Igknight",
  "Aroma",
  "Empowered Warrior",
  "Aether",
  "Prediction Princess",
  "Aqua",
  "Aquaactress",
  "Aquarium",
  "Chaos",
  "Black Luster Soldier",
  "Majespecter",
  "Graydle",
  "Kozmo",
  "Kaiju",
  "Paleozoic",
  "Dante",
  "Destruction Sword",
  "Buster Blader",
  "Dinomist",
  "Shiranui",
  "Shiranui Spectralsword",
  "Dracoverlord",
  "Phantom Knights",
  "The Phantom Knights",
  "Super Quant",
  "Super Quantum",
  "Super Quantal Mech Beast",
  "Blue-Eyes",
  "Exodia",
  "Lunalight",
  "Amorphage",
  "Metalfoes",
  "Triamid",
  "Cubic",
  "Celtic Guard",
  "Cipher",
  "Flower Cardian",
  "Silent Swordsman",
  "Silent Magician",
  "Magna Warrior",
  "Crystron",
  "Chemicritter",
  "Abyss",
  "Abyss Actor",
  "Abyss Script",
  "Subterror",
  "Subterror Behemoth",
  "SPYRAL",
  "SPYRAL GEAR",
  "SPYRAL MISSION",
  "Darklord",
  "Windwitch",
  "Zoodiac",
  "Pendulum",
  "Pendulum Dragon",
  "Pendulumgraph",
  "Predap",
  "Predaplant",
  "Invoked",
  "Gandora",
  "Skyscraper",
  "Lyrilusc",
  "Supreme King",
  "Supreme King Gate",
  "Supreme King Dragon",
  "True King",
  "Phantasm Spiral",
  "Gouki",
  "Trickstar",
  "World Chalice",
  "World Legacy",
  "Clear Wing",
  "Bonding -",
  "Code Talker",
  "Rokket",
  "Altergeist",
  "Krawler",
  "Metaphys",
  "Vendread",
  "F.A.",
  "Magical Musket",
  "The Weather",
  "Parshath",
  "Tindangle",
  "Mekk-Knight",
  "Mythical Beast",
  "Evolution Pill",
  "Borrel",
  "Eyes Restrict",
  "Armed Dragon",
  "Knightmare",
  "Elemental Lord",
  "Fur Hire",
  "Sky Striker",
  "Sky Striker Ace",
  "Crusadia",
  "Impcantation",
  "Cynet",
  "Salamangreat",
  "Dinowrestler",
  "Orcust",
  "Thunder Dragon",
  "Forbidden",
  "Danger!",
  "Nephthys",
  "Prank-Kids",
  "Mayakashi",
  "Valkyrie",
  "Rose Dragon",
  "Machine Angel",
  "Smile",
  "Time Thief",
  "Infinitrack",
  "Witchcrafter",
  "Evil Eye",
  "Endymion",
  "Marincess",
  "Tenyi",
  "Simorgh",
  "Fortune Fairy",
  "Battlewasp",
  "Hakai",
  "Hakaishin",
  "rocesslayer"
];
var AnimeArchetypes = [
  "Blackwing Tamer",
  "Advanced Crystal Beast",
  "Number S",
  "Melodious Songstress",
  "Cubic Seed",
  "Abyss Costume",
  "Speed Spell",
  "Alchemy Beast",
  "Alligator",
  "Anti",
  "Assassin",
  "Astral",
  "Atlandis",
  "Attack",
  "Baby",
  "Barian",
  "Barian's",
  "Battleguard",
  "Beastborg",
  "Butterfly",
  "Phantom Butterfly",
  "Carrier",
  "Cat",
  "Cat Girl",
  "Cicada",
  "Clear",
  "Comics Hero",
  "Cookpal",
  "Royal Cookpal",
  "Dart",
  "Dice",
  "Dizzy",
  "Dog",
  "Doll",
  "Doll Monster",
  "Doll Part",
  "Doodle",
  "Doodle Beast",
  "Dyson",
  "Earth",
  "Earthbound",
  "Earthbound Servant",
  "Elf",
  "Magic Elf",
  "Fairy",
  "Forbidden Beast",
  "Forest",
  "Fortune Fairy",
  "Fossil",
  "Fossil Knight",
  "Cenozoic",
  "Cenozoic Fossil Knight",
  "Mezozoic",
  "Mezozoic Fossil Knight",
  "Paleozoic",
  "Paleozoic Fossil Knight",
  "Gorgonic",
  "Goyo",
  "Granel",
  "Granel Attack",
  "Granel Guard",
  "Granel Top",
  "Granel Carrier",
  "Guard",
  "Guts Master",
  "Hand",
  "Heart Monster",
  "Heavy Industry",
  "Inu",
  "Ivy",
  "Jester",
  "Jester Puppet",
  "Jutte",
  "Kabuki Stage",
  "King",
  "Champion",
  "Knight",
  "Clock Knight",
  "Koala",
  "Landstar",
  "Magnet",
  "Mantis",
  "Mosquito",
  "Motor",
  "Neko",
  "Stray Cat",
  "Numeron",
  "Numeronius",
  "Papillon",
  "Parasite",
  "Pixie",
  "Priestess",
  "Puppet",
  "Quiz",
  "Quiz Panel",
  "Raccoon",
  "Red",
  "Rose",
  "Seal",
  "Shaman",
  "Shark",
  "Shining",
  "Skiel",
  "Skiel Attack",
  "Skiel Guard",
  "Skiel Top",
  "Skiel Carrier",
  "Sky",
  "Angel",
  "Celestial",
  "Slime",
  "Sphere",
  "Spice",
  "Spell Spice",
  "Spirit",
  "Spirit Crystal",
  "Starship",
  "Statue",
  "Pendulumstatue",
  "Stone",
  "Strain",
  "Tachyon",
  "Tachyon Dragon",
  "Thorn Prisoner",
  "Top",
  "Toy (Arc-V)",
  "Toy",
  "V",
  '"V "/" V"',
  "Vigilante",
  "White",
  "White Knight",
  "Wicked Rune",
  "Wisel",
  "Wisel Attack",
  "Wisel Guard",
  "Wisel Top",
  "Wisel Carrier",
  "Yubel",
  "∞",
  "Yomi",
  "Shogi/ Line Monster",
  "Hunder",
  "Heraldic",
  "Hell",
  "C",
  "Eco Spell",
  "Junk Robot",
  "W",
  "X",
  "Y",
  "Z",
  "Dark Mummy",
  "Tentacluster",
  "Monarch (monster)",
  "Mirror Imagine",
  "Hellix",
  "Sunavalon",
  "Sunvine",
  "Starving Venemy",
  "Hydradrive",
  "Armatos Legio",
  "D-Scale",
  "Stormrider",
  "Drone",
  "Codebreaker",
  "Dark Tuner",
  "Dark Synchro",
  "Darkness"
];
var chover = [];
var coiso = chover.length;
function teste1() {
  var treco = document.getElementById("Check");
  if (treco.checked == true){
    Array.prototype.unshift.apply(chover, Archetypes);
    coiso = chover.length;
  } else {
      chover.splice(0,395);
      coiso = chover.length;
  }
}
function teste2() {
    var treco2 = document.getElementById("Check");
    var treco = document.getElementById("Check2");
    if (treco.checked == true){
      Array.prototype.push.apply(chover, AnimeArchetypes);
      coiso = chover.length;
    } else { if (treco2.checked == false){
      chover.splice(0,169);
      coiso = chover.length;
    }else{
      chover.splice(395,169);  
      coiso = chover.length;
    }
  }
}
function Randomize() {
    var mene = Math.floor((Math.random() * coiso));
    if (chover.length == 0) {
      document.getElementById("demo").innerHTML = "Select at least one of the options below"
    }else{
    document.getElementById("demo").innerHTML =  '"'+chover[mene]+'"' + " Archetype"
    }
};
//https://www.reddit.com/user/JuquinhaDaVila